spring:
  profiles:
    active: dev
  aop:
    auto: true
    proxy-target-class: false
  servlet:
    # 上传文件大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

# mybatis路径
mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath:mapper/custom/*.xml
  type-aliases-package: com.gd.business.dao
