server:
    port: 8080

spring:
    application:
        name: business
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            url: jdbc:mysql://xxx.xxx.xx.xxx:3306/test
            username: root
            # 已加密
            password: F1Z2l7LOliX+LnfuLX1eluOjZy4SOVVS5lasoq/fToYnNhUZVEIHseT/W5YRyR43OwzitgDSlHlGbVeZKSLMLA==
            # 配置连接池初始化大小、最大、最小
            initial-size: 5
            max-active: 20
            min-idle: 5
            # 配置获取连接等待超时的时间
            max-wait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            time-between-eviction-runs-millis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
#            filters: stat
            filter:
                config:
                    enabled: true
            connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNJ2NeNTeab0xkHr4P5EY5ah2AZuQjPu+zWb+RStDLFy/kcnz48cEjOEwmEPR2rJ0XgSRWCLNWSicicfkcqfBcCAwEAAQ==
# 日志等级
logging:
    level.com.gd.business.'*'.dao: debug