server:
    port: 8080

spring:
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        primary:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/test?useUnicode=true&characterEncoding=utf8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
            username: xx
            password: xxxx
            type: com.alibaba.druid.pool.DruidDataSource
            #druid相关配置
            druid:
                #监控统计拦截的filters
                filters: stat
                #配置初始化大小/最小/最大
                initial-size: 1
                min-idle: 1
                max-active: 20
                #获取连接等待超时时间
                max-wait: 60000
                #间隔多久进行一次检测，检测需要关闭的空闲连接
                time-between-eviction-runs-millis: 60000
                #一个连接在池中最小生存的时间
                min-evictable-idle-time-millis: 300000
                #这是mysql数据库写法 如果是Oracle则应该写为：select 1 from dual
                validation-query: SELECT 'x'
                test-while-idle: true
                #在获取连接的时候是否去检测这个连接是否正常工作,默认为true,这里设置为不检测
                test-on-borrow: false
                test-on-return: false
                #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
                pool-prepared-statements: false
                max-pool-prepared-statement-per-connection-size: 20
        two:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/test2?useUnicode=true&characterEncoding=utf8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
            username: xxx
            password: xxxx
            type: com.alibaba.druid.pool.DruidDataSource
            #druid相关配置
            druid:
                #监控统计拦截的filters
                filters: stat
                #配置初始化大小/最小/最大
                initial-size: 1
                min-idle: 1
                max-active: 20
                #获取连接等待超时时间
                max-wait: 60000
                #间隔多久进行一次检测，检测需要关闭的空闲连接
                time-between-eviction-runs-millis: 60000
                #一个连接在池中最小生存的时间
                min-evictable-idle-time-millis: 300000
                #这是mysql数据库写法 如果是Oracle则应该写为：select 1 from dual
                validation-query: SELECT 'x'
                test-while-idle: true
                #在获取连接的时候是否去检测这个连接是否正常工作,默认为true,这里设置为不检测
                test-on-borrow: false
                test-on-return: false
                #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
                pool-prepared-statements: false
                max-pool-prepared-statement-per-connection-size: 20


logging:
    level:
        #打印SQL信息
        com.along.dao: debug